initial_position:
  joint_h_bl: 0
  joint_hip_femur_bl: 0
  joint_femur_tibia_bl: 0
  joint_h_br: 0
  joint_hip_femur_br: 0
  joint_femur_tibia_br: 0
  joint_h_fl: 0
  joint_hip_femur_fl: 0
  joint_femur_tibia_fl: 0
  joint_h_fr: 0
  joint_hip_femur_fr: 0
  joint_femur_tibia_fr: 0