moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
moveit_simple_controller_manager:
  controller_names:
    - back_left_leg_controller
    - back_right_leg_controller
    - front_left_leg_controller
    - front_right_leg_controller

  back_left_leg_controller: 
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_h_bl
      - joint_hip_femur_bl
      - joint_femur_tibia_bl

  back_right_leg_controller: 
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_h_br
      - joint_hip_femur_br
      - joint_femur_tibia_br

  front_left_leg_controller: 
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_h_fl
      - joint_hip_femur_fl
      - joint_femur_tibia_fl

  front_right_leg_controller: 
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_h_fr
      - joint_hip_femur_fr
      - joint_femur_tibia_fr
