moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
moveit_simple_controller_manager:
  controller_names:
    - fl_leg_controller
    - fr_leg_controller
    - bl_leg_controller
    - br_leg_controller

  fl_leg_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - fl_hip
      - fl_femur
      - fl_tibia

  fr_leg_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - fr_hip
      - fr_femur
      - fr_tibia

  bl_leg_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - bl_hip
      - bl_femur
      - bl_tibia

  br_leg_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - br_hip
      - br_femur
      - br_tibia
