controller_manager:
  ros__parameters:
    update_rate: 50

    front_right_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    front_left_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    back_right_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    back_left_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

front_right_leg_controller:
  ros__parameters:
    joints:
      - joint_h_fr
      - joint_hip_femur_fr
      - joint_femur_tibia_fr
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true
    allow_integration_in_goal_trajectories: true

front_left_leg_controller:
  ros__parameters:
    joints:
      - joint_h_fl
      - joint_hip_femur_fl
      - joint_femur_tibia_fl
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true
    allow_integration_in_goal_trajectories: true

back_right_leg_controller:
  ros__parameters:
    joints:
      - joint_h_br
      - joint_hip_femur_br
      - joint_femur_tibia_br
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true
    allow_integration_in_goal_trajectories: true

back_left_leg_controller:
  ros__parameters:
    joints:
      - joint_h_bl
      - joint_hip_femur_bl
      - joint_femur_tibia_bl
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
